get:
  summary: Get a single data export destination by ID
  operationId: getDestination
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
    - $ref: ../components/parameters/DestinationId.yaml
  responses:
    '200':
      $ref: ../components/responses/Destination2xx.yaml
    '401':
      $ref: ../components/responses/Standard401.yaml
    '404':
      $ref: ../components/responses/Standard404.yaml
  tags:
    - Data export destinations
patch:
  summary: Perform a partial update to a data export destination.
  operationId: patchDestination
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
    - $ref: ../components/parameters/DestinationId.yaml
  requestBody:
    $ref: ../components/requestBodies/PatchOperationArray2.yaml
  responses:
    '200':
      $ref: ../components/responses/Destination2xx.yaml
    '400':
      $ref: ../components/responses/Standard400.yaml
    '401':
      $ref: ../components/responses/Standard401.yaml
    '404':
      $ref: ../components/responses/Standard404.yaml
    '409':
      $ref: ../components/responses/Standard409.yaml
  tags:
    - Data export destinations
delete:
  summary: Get a single data export destination by ID
  operationId: deleteDestination
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
    - $ref: ../components/parameters/DestinationId.yaml
  responses:
    '204':
      $ref: ../components/responses/Standard204.yaml
    '401':
      $ref: ../components/responses/Standard401.yaml
    '404':
      $ref: ../components/responses/Standard404.yaml
  tags:
    - Data export destinations
