get:
  operationId: getFeatureFlagChangeRequest
  summary: Get a single change request for a feature flag
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/FeatureFlagKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
    - $ref: ../components/parameters/FeatureFlagChangeRequestId.yaml
  responses:
    '200':
      description: Feature flag change request response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/FeatureFlagChangeRequests.yaml
    '401':
      $ref: ../components/responses/Standard401.yaml
    '404':
      $ref: ../components/responses/Standard404.yaml
  tags:
    - Feature flags
