get:
  summary: Get an environment given a project and key.
  operationId: getEnvironment
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
  responses:
    '200':
      $ref: ../components/responses/Environment2xx.yaml
    '401':
      $ref: ../components/responses/Standard401.yaml
    '404':
      $ref: ../components/responses/Standard404.yaml
  tags:
    - Environments
patch:
  summary: Modify an environment by ID.
  operationId: patchEnvironment
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
  requestBody:
    $ref: ../components/requestBodies/PatchOperationArray.yaml
  responses:
    '200':
      $ref: ../components/responses/Environment2xx.yaml
    '400':
      $ref: ../components/responses/Standard400.yaml
    '401':
      $ref: ../components/responses/Standard401.yaml
    '404':
      $ref: ../components/responses/Standard404.yaml
    '409':
      $ref: ../components/responses/Standard409.yaml
  tags:
    - Environments
delete:
  summary: Delete an environment in a specific project.
  operationId: deleteEnvironment
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
  responses:
    '204':
      $ref: ../components/responses/Standard204.yaml
    '401':
      $ref: ../components/responses/Standard401.yaml
    '404':
      $ref: ../components/responses/Standard404.yaml
  tags:
    - Environments
