post:
  summary: Reset an environment's SDK key with an optional expiry time for the old key.
  operationId: resetEnvironmentSDKKey
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
    - $ref: ../components/parameters/EnvironmentSDKKeyExpiry.yaml
  responses:
    '200':
      $ref: ../components/responses/Environment2xx.yaml
    '404':
      $ref: ../components/responses/Standard404.yaml
    '409':
      $ref: ../components/responses/Standard409.yaml
  tags:
    - Environments
