post:
  operationId: postApplyFeatureFlagChangeRequest
  summary: Apply change request for a feature flag
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/FeatureFlagKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
    - $ref: ../components/parameters/FeatureFlagChangeRequestId.yaml
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            comment:
              type: string
              description: comment will be included in audit log item for change.
              example: Applying approved changes
    description: Apply a new feature flag change request
    required: true
  responses:
    '200':
      description: Feature flag change request applied response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/FeatureFlagChangeRequests.yaml
    '401':
      $ref: ../components/responses/Standard401.yaml
    '404':
      $ref: ../components/responses/Standard404.yaml
  tags:
    - Feature flags
