get:
  summary: >-
    List all users in the environment. Includes the total count of users. In
    each page, there will be up to 'limit' users returned (default 20). This is
    useful for exporting all users in the system for further analysis. Paginated
    collections will include a next link containing a URL with the next set of
    elements in the collection.
  operationId: getUsers
  parameters:
    - $ref: ../components/parameters/ProjectKey.yaml
    - $ref: ../components/parameters/EnvironmentKey.yaml
    - $ref: ../components/parameters/Limit.yaml
    - $ref: ../components/parameters/HMAC.yaml
    - $ref: ../components/parameters/ScrollId.yaml
  responses:
    '200':
      description: Users response.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Users.yaml
    '401':
      $ref: ../components/responses/Standard401.yaml
  tags:
    - Users
