name: expiry
in: query
required: false
description: >-
  An expiration time for the old environment SDK key, expressed as a Unix epoch
  time in milliseconds. By default, the key will expire immediately.
schema:
  type: integer
  format: int64
